name: PR to main branch updated
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  Build-Test:
    runs-on: ubuntu-latest
    if: ${{ github.base_ref == 'main' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build --release --all-features
